server:
  port: 9100

  
spring:
  application:
    name: "product-catalogue-ms"
  profiles:
    active: "prod"
  data:
     mongodb :
        host: localhost
        port: 27017
        database : product_catalouge
        #username : 
        #password : 
  config:
    import: "optional:configserver:http://localhost:8071/"


logging:
   level:
      root: INFO

build:
  version: 1.2

management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
      
endpoints:
  shutdown:
    enabled: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
#  Some information will be shown inside Eureka dashboard 
info:
  app:
    name: "product-catalogue-ms"
    description: "Product Catalouge Application"
    version: "1.0.0"

